addons:
  sonarqube: true
jdk:
  - oraclejdk8
env:
  global:
    secure: ZVme7bez6+KfZ7gPCHDaS3LmGUW1L5mkD9yQUJyfw9/gDEgFDWopOIgmbQIxRcbZeanr3WEm75AvK5IjrgGvSJi4XLgHqa6fTPRYPYWgpgidfPsi0WgW/37bRbUE5nnvdFEciMVlWEUTnChz05Xwi8Mq0UsbCOEvkzh6dziQhd/KkMbe5ydfjB0bYSVvjJcggVpVz66VoUUi12DPS2sZCu8S/yXz9WUspOZ2ueU5JGdqqo+cUXDDLjSncZcoXujHJkLnbkpnqCG4XKMhhQJVOWf1P6IhpNbg2zy8GX/0UOXrkyQWVqYCQ4bfo4yhrCoA3jGsQBEfoc/vTOnEnSeUeyNoJZZQD2nVfo1AVINZIEqcP3k6Z5LImGpegsoRGMv7nSjHWCvpWLAMa+NIpW1oHAewcCVjVNtTEiNPSBc02/F6ceqYAQHQlgiO5GQJak3FxYUzLrE4q+QDz2qmwgvDQHUWccZlacEupWHsfQEki4GsnaswsBlX7dT5jUJUUiUc5ltBT6SutjzZRcbYhehO8oQeZ3l5cwenD+5cYZZqlVKQbeuCbtmeOssRHig3TU9NnRFKwKXJWM0Wyy/TgWHoHWyx6Apl2Sis7o6wiPu3K9gC6kLjIRLTh1b+xxLXk0XZzYqYBRbGlJO8D8U2P6nqJf71SDO4/3eTGJtfxvQPc/s=
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN
